domain: shockeos.github.io
#url: https://shock.international
url: https://shockeos.github.io
baseurl: 

# Site settings
title: SHOCK Electro-Optic Systems
email: info@shockeos.com
description: "Design services for electro optic products in the defence industry for land, air and naval platforms"


# Team names, titles and social links
people:
- name: Sencer Sahin
  pic: Sencer_photo
  position: Co-founder and CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sencer-%C5%9Fahin-0115823b/
    #- title: facebook
    #  url: #
    #- title: stack-overflow
    #  url: #

- name: Kobus Coetzee
  pic: Kobus_photo
  position: Co-founder and CTO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kobusengineer/
    #- title: facebook
    #  url: #
    #- title: linkedin
    #  url: #

- name: Herman Nel
  pic: herman_photo
  position: Co-founder and CFO
  social:
  - title: linkedin
      url: https://www.linkedin.com/in/herman-nel-9a002a47/
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
